name: Build and Push crkbd
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://qmkfm/base_container:latest
    steps:
    - name: Checkout qmk/qmk_firmware:master
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: master
        submodules: true
    - name: Build firmware
      run: |
        make crkbd/rev1/common:default
        make crkbd/rev1/common:via
        make foostan/cornelius:default
        make foostan/cornelius:via
    - name: Save hex files
      uses: actions/upload-artifact@v1
      with:
        name: .build
        path: .build
  commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Load hex files
      uses: actions/download-artifact@v1
      with:
        name: .build
    - name: Commit and Push
      run: |
        git add .
        git commit -m "Update hex files"
        git push origin main
