name: Build and Push crkbd
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://qmkfm/base_container:latest
    steps:
    - name: Checkout qmk/qmk_firmware:master
      uses: actions/checkout@v2
      with:
        repository: qmk/qmk_firmware
        ref: master
        submodules: true
    - name: Build firmware
      run: |
        make crkbd/rev1/common:via
    - name: Save hex
      uses: actions/upload-artifact@v1
      with:
        name: tmp
        path: .build/crkbd_rev1_common_via.hex
  commit:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Load hex
      uses: actions/download-artifact@v1
      with:
        name: tmp
    - name: Commit and Push
      run: |
        mkdir -p build
        mv tmp/crkbd_rev1_common_via.hex build
        git add build
        git commit -m "Update crkbd_rev1_common_via.hex"
        git push origin main
